name: Release
on:
  push:
    tags:
      - "*"

env:
  MILL_PGP_SECRET_BASE64: ${{ secrets.PGP_SECRET }}
  MILL_PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  MILL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  MILL_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  tests:
    uses: ./.github/workflows/ci.yml
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'sake92/mill-squery'
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Publish
        run: >
          ./mill -i mill.scalalib.SonatypeCentralPublishModule/publishAll \
              --publishArtifacts __.publishArtifacts \
              --readTimeout 600000 \
              --awaitTimeout 600000
